---
ansible_connection: local

functions:
  config_host:
    - name=$1
    - shift
    - ansible-playbook playbook.yml -e "host_override=$name" "$@"

ssh_host_common_configs:
  ControlMaster: "auto"
  ControlPath: "~/.ssh/%r@%h:%p"
  ControlPersist: "5m"

use_tmux: true
use_vscode_git: false
