---
- name: template bash_profile
  template:
    src: bash.profile.j2
    dest: '{{ home_dir }}/.bash_profile'
    owner: '{{ user }}'
    group: '{{ group }}'
- name: template bashrc
  template:
    src: bashrc.j2
    dest: '{{ home_dir }}/.bashrc'
    owner: '{{ user }}'
    group: '{{ group }}'
