---
- name: setup i3 config
  copy:
    src: i3.conf
    dest: '{{ home_dir }}/.config/i3/config'
    owner: '{{ user }}'
    group: '{{ group }}'
- name: setup i3status config
  copy:
    src: i3status.conf
    dest: '{{ home_dir }}/.config/i3status/config'
    owner: '{{ user }}'
    group: '{{ group }}'
