---
- name: make vnc directory
  file:
    path: '{{ home_dir }}/.vnc'
    state: directory
    owner: '{{ user }}'
    group: '{{ group }}'
- name: copy vnc xstartup
  copy:
    src: xstartup.sh
    dest: '{{ home_dir }}/.vnc/xstartup'
    owner: '{{ user }}'
    group: '{{ group }}'
    mode: '0755'
