---
all:
  children:
    grnoc:
      children:
        bastion:
          hosts:
            skip.grnoc.iu.edu:
        internal:
          children:
            compute:
              children:
                compute_bldc:
                  hosts:
                    compute.cloud.bldc.grnoc.iu.edu:
                    compute2.cloud.bldc.grnoc.iu.edu:
                    compute3.cloud.bldc.grnoc.iu.edu:
                    compute4.cloud.bldc.grnoc.iu.edu:
                    compute5.cloud.bldc.grnoc.iu.edu:
                compute_ctc:
                  hosts:
                    compute.cloud.ctc.grnoc.iu.edu:
                    compute2.cloud.ctc.grnoc.iu.edu:
                    compute3.cloud.ctc.grnoc.iu.edu:
                    compute4.cloud.ctc.grnoc.iu.edu:
                    compute5.cloud.ctc.grnoc.iu.edu:
          hosts:
            backup.grnoc.iu.edu:
            backup.ictc.ilight.net:
            build.grnoc.iu.edu:
            db2.grnoc.iu.edu:
            frontend.tsds.bldc.grnoc.iu.edu:
            frontend.tsds.ctc.grnoc.iu.edu:
            io3.bldc.grnoc.iu.edu:
            jdratlif-dev7.ctc.grnoc.iu.edu:
            mongo-arbiter.areon.net:
            simp-comp.bldc.grnoc.iu.edu:
            simp-data2.bldc.grnoc.iu.edu:
            simp-poller.bldc.grnoc.iu.edu:
            snapp.frcy.areon.net:
            snapp.fyvl.areon.net:
            snapp.oshean.org:
            snapp.net.cen.ct.gov:
            snapp.noc.onenet.net:
            snapp-test-01.globalnoc.mcnc.org:
            snapp-collector-01.globalnoc.mcnc.org:
            snapp-collector-02.globalnoc.mcnc.org:
            snapp-collector-test-01.globalnoc.mcnc.org:
            snapp-frontend-01.globalnoc.mcnc.org:
            snapp-frontend-02.globalnoc.mcnc.org:
            snapp-frontend-test-01.globalnoc.mcnc.org:
            snapp-portal-01.globalnoc.mcnc.org:
            snapp-portal-02.globalnoc.mcnc.org:
            snapp-portal-test-01.globalnoc.mcnc.org:
            snapp-rabbit-01.globalnoc.mcnc.org:
            snapp-rabbit-02.globalnoc.mcnc.org:
            snapp-rabbit-test-01.globalnoc.mcnc.org:
            snapp-services-01.globalnoc.mcnc.org:
            snapp-services-02.globalnoc.mcnc.org:
            snapp-services-test-01.globalnoc.mcnc.org:
            snapp-shard-01.globalnoc.mcnc.org:
            snapp-shard-02.globalnoc.mcnc.org:
            snapp-shard-test-01.globalnoc.mcnc.org:
        i2:
          hosts:
            backup.ctc.net.internet2.edu:
            frontend.tsds.bldc.net.internet2.edu:
            frontend.tsds.wash2.net.internet2.edu:
            mongo1.tsds.bldc.net.internet2.edu:
            mongo2.tsds.bldc.net.internet2.edu:
            mongo3.tsds.bldc.net.internet2.edu:
            mongo1.tsds.wash2.net.internet2.edu:
            mongo2.tsds.wash2.net.internet2.edu:
            mongo3.tsds.wash2.net.internet2.edu:
            rabbitmq.tsds.bldc.net.internet2.edu:
            rabbitmq.tsds.wash2.net.internet2.edu:
            services.tsds.bldc.net.internet2.edu:
            services.tsds.wash2.net.internet2.edu:
            snapp-collector.bldc.net.internet2.edu:
            snapp-collector.wash2.net.internet2.edu:
            vn.bldc.net.internet2.edu:
            vn.wash2.net.internet2.edu:
    xaiver:
      hosts:
        htpc:
