---
aliases:
  rpm6: 'rpm --define="_gpg_name syseng@grnoc.iu.edu"'
  rpm7: 'rpm --define="_gpg_name globalnoc@iu.edu"'
  # vpn: >-
  #   sudo openconnect --juniper
  #   -s "vpn-slice 10.0.0.0/8 {{ vpn_hosts | join(' ') }}"
  #   -u jdratlif https://vpn.iu.edu/groups

functions:
  yaml_class:
    - for f in *.eyaml; do
    -   yq e '.classes[] | select(. == '\"$1\"')' $f 2> /dev/null | grep $1 > /dev/null
    -   if [ $? == 0 ]; then echo $f; fi
    - done

keychain_bin: '/usr/local/bin/keychain'

ssh_host_configs:
  xaiver:
    Hostname: 'xaiver.technoplaza.net'
    Port: '2202'
    RemoteForward: '192.168.1.5:9922 localhost:22'

use_i3: false
use_keychain: false
use_vnc: false
use_vscode_git: true

vpn_hosts:
  - account.net.internet2.edu
  - account.noc.onenet.net
  - awx.grnoc.iu.edu
  - awx-test.bldc.grnoc.iu.edu
  - awx.bldc.nwave.noaa.gov
  - awx.ctc.nwave.noaa.gov
  - build.grnoc.iu.edu
  - cni-mapper.grnoc.iu.edu
  - cni-mapper-bl.grnoc.iu.edu
  - cosign.areon.net
  - cloud.grnoc.iu.edu
  - cloud.bldc.grnoc.iu.edu
  - cloud.ctc.grnoc.iu.edu
  - footprints.ncren.net
  - oob2.ak23.bldc.grnoc.iu.edu
  - oob2.n13.ctc.grnoc.iu.edu
  - os.bldc.net.internet2.edu
  - os.wash2.net.internet2.edu
  - nessus.boul.nwave.noaa.gov
  - snapp.ncren.net
  - snapp-frontend-01.globalnoc.mcnc.org
  - snapp-frontend-02.globalnoc.mcnc.org
  - snapp-frontend-test-01.globalnoc.mcnc.org
  - snapp-services-01.globalnoc.mcnc.org
  - snapp-services-02.globalnoc.mcnc.org
  - snapp-services-test-01.globalnoc.mcnc.org
  - weblogin.grnoc.iu.edu
  - weblogin.net.cen.ct.gov
  - weblogin.oshean.org
  - weblogin.nwave.noaa.gov
