---
aliases:
  fix_perms: 'find . -type f -exec chmod 644 {} \; ; find . -type d -exec chmod 755 {} \;'
  git_oneline: 'git log --oneline'
  ls: 'ls --color=auto'
  ll: 'ls -l --color=auto'
  ipt: 'sudo iptables --line-numbers -n -v -L'

ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDeoc+6JVSKxb0AY/HlibPQF1zqblGXVuPouktAao3f1oXJqylkKavXCoIMTAI6TH9AVtr6eBO/cdU6vDr1YT5KXl4R77J4ra2w+U3jByacQNirnJcU3TblJaQ+j3IUqohDLHdtMTJfwKRDAoecAsKU7Cb1facGiCIoaVmr4KnXOowSvLxBVVlMiiTZcPxQuvYuouAy2cQYeoTmzt8f1jorQU76W+UBOWoXETakmKWUc1KRirEQV7WuNW8nWNbzTE2p3sHgVmTiRdTtusqjra0pdKDh3koXC7e6uRod7U3DtwONueTXUOv/AalvypD80hQpLvl1tsnTjLwFJFQfuohjr0gHncam5pwbCUlcycIVhLt0hK6Odl5x7meS/CRND7AuumMyPjUwKwo/janynd+60waS4dricCvBpAH0nhYgy+jlvWNRtzEDolsh7rhUlUyLrqP9A41GtsGG3zf4OenKx0hEptZrJS6N00coLGzt+CnEAGn890+th2jiwj1eQcM= jdratlif@jdratlif-yoga2

ssh_host_common_configs:
  ServerAliveCountMax: 3
  ServerAliveInterval: 30
