---
aliases:
  fix_perms: 'find . -type f -exec chmod 644 {} \; ; find . -type d -exec chmod 755 {} \;'
  ls: "ls --color=auto"
  ll: "ls -l --color=auto"
  ipt: "sudo iptables --line-numbers -n -v -L"

functions:
  del_known_host:
    - LINE_NUMBER=$1
    - "[[ ! -z $LINE_NUMBER ]] && sed -i -e $1d ~/.ssh/known_hosts"
  fix_agent:
    - MY_DIR=$(ls -ldt /tmp/ssh-* | grep jdratlif | head -1 | awk '{print $NF}')
    - MY_AGENT=$(ls ${MY_DIR}/agent*)
    - export SSH_AUTH_SOCK=$MY_AGENT

ssh_authorized_keys: []

ssh_host_common_configs:
  ServerAliveCountMax: 3
  ServerAliveInterval: 30
