---
ansible_connection: local

functions:
  config_host:
    - name=$1
    - shift
    - ansible-playbook main.yaml -e "host_override=$name" "$@"
  fix_agent:
    - MY_DIR=$(ls -ldt /tmp/ssh-* | grep jdratlif | head -1 | awk '{print $NF}')
    - MY_AGENT=$(ls ${MY_DIR}/agent*)
    - export SSH_AUTH_SOCK=$MY_AGENT

ssh_host_common_configs:
  ControlMaster: 'auto'
  ControlPath: '~/.ssh/%r@%h:%p'

ssh_host_configs:
  # AREON hosts

  areon-grafana:
    Hostname: grafana.areon.net

  # SNAPP servers
  areon-snapp areon-snapp-1 areon-snapp-frcy:
    Hostname: snapp.frcy.areon.net
  areon-snapp-2 areon-snapp-fyvl:
    Hostname: snapp.fyvl.areon.net

  # CEN hosts

  # carto host
  'cen-carto':
    Hostname: carto.net.cen.ct.gov

  # nagios servers
  'cen-mon-bldc cen-mon':
    Hostname: mon.bldc.net.cen.ct.gov
  cen-mon-ehct:
    Hostname: mon.ehct.net.cen.ct.gov

  # grafana servers
  cen-grafana:
    Hostname: grafana.net.cen.ct.gov

  # SNAPP servers
  cen-snapp:
    Hostname: snapp.net.cen.ct.gov

  # internal hosts

  # BURP servers
  burp:
    Hostname: backup.grnoc.iu.edu
  burp-ctc:
    Hostname: backup.ictc.ilight.net

  # GlobalNOC cloud
  cloud-bldc-1:
    Hostname: compute.cloud.bldc.grnoc.iu.edu
  cloud-bldc-2:
    Hostname: compute2.cloud.bldc.grnoc.iu.edu
  cloud-bldc-3:
    Hostname: compute3.cloud.bldc.grnoc.iu.edu
  cloud-bldc-4:
    Hostname: compute4.cloud.bldc.grnoc.iu.edu
  cloud-bldc-5:
    Hostname: compute5.cloud.bldc.grnoc.iu.edu
  cloud-bldc-6:
    Hostname: compute6.cloud.bldc.grnoc.iu.edu
  cloud-bldc-7:
    Hostname: compute7.cloud.bldc.grnoc.iu.edu
  cloud-ctc-1:
    Hostname: compute.cloud.ctc.grnoc.iu.edu
  cloud-ctc-2:
    Hostname: compute2.cloud.ctc.grnoc.iu.edu
  cloud-ctc-3:
    Hostname: compute3.cloud.ctc.grnoc.iu.edu
  cloud-ctc-4:
    Hostname: compute4.cloud.ctc.grnoc.iu.edu
  cloud-ctc-5:
    Hostname: compute5.cloud.ctc.grnoc.iu.edu
  cloud-ctc-6:
    Hostname: compute6.cloud.ctc.grnoc.iu.edu
  cloud-ctc-7:
    Hostname: compute7.cloud.ctc.grnoc.iu.edu

  # dev servers
  dev:
    Hostname: jdratlif-dev7.ctc.grnoc.iu.edu
    LocalForward:
      - '24478 localhost:5901'
      - '24422 localhost:22'
  dev2:
    Hostname: jdratlif-dev7.bldc.grnoc.iu.edu

  # DNS servers
  dns:
    Hostname: db2.grnoc.iu.edu

  # Frontend servers
  'frontend-bldc frontend':
    Hostname: frontend.tsds.bldc.grnoc.iu.edu
  frontend-ctc:
    Hostname: frontend.tsds.ctc.grnoc.iu.edu

  # grafana servers
  'btaa-grafana':
    Hostname: grafana.omnipop.btaa.org
  'caaren-grafana':
    Hostname: grafana.caaren.grnoc.iu.edu
  'campuses-grafana':
    Hostname: grafana.campuses.grnoc.iu.edu
  'gigapop-grafana':
    Hostname: grafana.indiana.gigapop.net
  'gpn-grafana':
    Hostname: grafana.gpn.grnoc.iu.edu
  'ilight-grafana':
    Hostname: grafana.ilight.net
  'intl-grafana':
    Hostname: grafana.intl.grnoc.iu.edu
  'iu-grafana':
    Hostname: grafana.net.uits.iu.edu
  'linkoregon-grafana':
    Hostname: grafana.linkoregon.org
  'pennren-grafana':
    Hostname: grafana.net.pennren.net
  'rt-grafana':
    Hostname: grafana.net.rt.iu.edu
  'sox-grafana':
    Hostname: grafana.sox.net

  # NAGIOS servers
  'mon-bldc mon nocmon':
    Hostname: nocmon.bldc.grnoc.iu.edu
  mon-ctc:
    Hostname: nocmon.ctc.grnoc.iu.edu

  # NetFlow servers
  netflow-dev-master:
    Hostname: netflow-dev-es-master-01.ctc.grnoc.iu.edu
  netflow-dev-agg-bldc:
    Hostname: netflow-dev-es-agg-01.bldc.grnoc.iu.edu
  netflow-dev-agg-ctc:
    Hostname: netflow-dev-es-agg-01.ctc.grnoc.iu.edu

  # oob devices
  oob-ak23 oob-ak23-1:
    Hostname: oob.ak23.bldc.grnoc.iu.edu
    Ciphers: aes256-cbc
    KexAlgorithms: diffie-hellman-group1-sha1
  oob-bc10 oob-bc10-1:
    Hostname: oob.bc10.bldc.grnoc.iu.edu
    Ciphers: aes256-cbc
    KexAlgorithms: diffie-hellman-group1-sha1
  oob-bc10-2:
    Hostname: oob.bc10.bldc.grnoc.iu.edu
    Ciphers: aes256-cbc
    KexAlgorithms: diffie-hellman-group1-sha1
  oob-n13:
    Hostname: oob.n13.ctc.grnoc.iu.edu
    Ciphers: aes256-cbc
    KexAlgorithms: diffie-hellman-group1-sha1

  # pdu devices
  pdu-bc10:
    User: grnoc
    Hostname: 10.240.3.15
    Ciphers: aes256-cbc
    HostKeyAlgorithms: ssh-dss
    KexAlgorithms: diffie-hellman-group1-sha1
  pdu-n13:
    User: grnoc
    Hostname: 10.241.3.54
    Ciphers: aes256-cbc
    HostKeyAlgorithms: ssh-dss
    KexAlgorithms: diffie-hellman-group1-sha1

  # puppet master
  puppet:
    Hostname: build.grnoc.iu.edu

  # rabbit hosts
  'rabbit-bldc rabbit':
    Hostname: rabbitmq.tsds.bldc.grnoc.iu.edu

  # TSDS services hosts
  'services-bldc services':
    Hostname: services.tsds.bldc.grnoc.iu.edu
  services-ctc:
    Hostname: services.tsds.ctc.grnoc.iu.edu

  # SIMP hosts
  'simp-comp simp-tsds':
    Hostname: simp-comp.bldc.grnoc.iu.edu
  simp-data:
    Hostname: simp-data2.bldc.grnoc.iu.edu
  simp-poller:
    Hostname: simp-poller.bldc.grnoc.iu.edu

  # SNAPP host
  snapp:
    Hostname: snapp.bldc.grnoc.iu.edu

  # Campus Network Switches
  switch-bldc-bc10:
    Hostname: 10.240.120.37
    User: cni_rancid

  switch-bldc-ak23:
    Hostname: 10.240.120.71
    User: cni_rancid

  switch-ctc-n13:
    Hostname: 10.241.120.43
    User: cni_rancid

  # Juniper VMX servers
  vmx:
    Hostname: 140.182.45.188
    User: root

  # Internet2 hosts

  # Bastion hosts
  'i2-bastion-bldc i2-bastion':
    Hostname: bastion.bldc.net.internet2.edu
  i2-bastion-wash2:
    Hostname: bastion.wash2.net.internet2.edu

  # BGP hosts
  'i2-bgp':
    Hostname: openbgp.wash2.net.internet2.edu
  'i2-bgp-old':
    Hostname: bgp.ctc.net.internet2.edu
  'i2-bgp-report':
    Hostname: bgp.ctc.grnoc.iu.edu

  # BURP servers
  'i2-burp-bldc i2-burp-wash2 i2-burp':
    Hostname: backup.ctc.net.internet2.edu

  # frontend servers
  'i2-frontend-bldc i2-frontend':
    Hostname: frontend.tsds.bldc.net.internet2.edu
  i2-frontend-wash2:
    Hostname: frontend.tsds.wash2.net.internet2.edu

  # grafana servers
  'i2-grafana-bldc i2-grafana':
    Hostname: grafana.bldc.net.internet2.edu
  i2-grafana-wash2:
    Hostname: grafana.wash2.net.internet2.edu

  # NAGIOS servers
  'i2-mon-bldc i2-mon i2-nocmon':
    Hostname: mon.bldc.net.internet2.edu
  'i2-mon-wash2 i2-nocmon-wash2':
    Hostname: mon.wash2.net.internet2.edu

  # mongo servers
  i2-mongo-bldc-1:
    Hostname: mongo1.tsds.bldc.net.internet2.edu
  i2-mongo-bldc-2:
    Hostname: mongo2.tsds.bldc.net.internet2.edu
  i2-mongo-bldc-3:
    Hostname: mongo3.tsds.bldc.net.internet2.edu

  i2-mongo-wash2-1:
    Hostname: mongo1.tsds.wash2.net.internet2.edu
  i2-mongo-wash2-2:
    Hostname: mongo2.tsds.wash2.net.internet2.edu
  i2-mongo-wash2-3:
    Hostname: mongo3.tsds.wash2.net.internet2.edu

  # rabbit servers
  'i2-rabbit-bldc i2-rabbit':
    Hostname: rabbitmq.tsds.bldc.net.internet2.edu
  i2-rabbit-wash2:
    Hostname: rabbitmq.tsds.wash2.net.internet2.edu

  # TSDS services servers
  'i2-services-bldc i2-services':
    Hostname: services.tsds.bldc.net.internet2.edu
  i2-services-wash2:
    Hostname: services.tsds.wash2.net.internet2.edu

  # SNAPP servers
  'i2-snapp-bldc i2-simp-bldc i2-snapp i2-simp':
    Hostname: snapp-collector.bldc.net.internet2.edu
  'i2-snapp-wash2 i2-simp-wash2':
    Hostname: snapp-collector.wash2.net.internet2.edu

  # Visual Network servers
  'i2-vn-bldc i2-vn':
    Hostname: vn.bldc.net.internet2.edu
  i2-vn-wash2:
    Hostname: vn.wash2.net.internet2.edu

  # old network devices
  sdn-dcp2.ashb.net.internet2.edu:
    KexAlgorithms: diffie-hellman-group1-sha1
    HostKeyAlgorithms: ssh-dss
    Ciphers: aes256-cbc

  # MCNC hosts

  # AlertMon servers
  'mcnc-alertmon-1 mcnc-alertmon':
    Hostname: mon-01.globalnoc.mcnc.org
  mcnc-alertmon-2:
    Hostname: mon-02.globalnoc.mcnc.org

  # frontend servers
  'mcnc-frontend-1 mcnc-frontend':
    Hostname: snapp-frontend-01.globalnoc.mcnc.org
  mcnc-frontend-2:
    Hostname: snapp-frontend-02.globalnoc.mcnc.org
  mcnc-frontend-test:
    Hostname: snapp-frontend-test-01.globalnoc.mcnc.org

  # kerberos servers
  'mcnc-kerb mcnc-kerb-1':
    Hostname: tools-01.globalnoc.mcnc.org

  # KVM servers
  'mcnc-kvm-1 mcnc-kvm':
    Hostname: snapp-01.globalnoc.mcnc.org
  mcnc-kvm-2:
    Hostname: snapp-02.globalnoc.mcnc.org
  mcnc-kvm-test:
    Hostname: snapp-test-01.globalnoc.mcnc.org

  # mongo servers
  'mcnc-mongo-1 mcnc-mongo mcnc-shard-1 mcnc-shard':
    Hostname: snapp-shard-01.globalnoc.mcnc.org
  'mcnc-mongo-2 mcnc-shard-2':
    Hostname: snapp-shard-02.globalnoc.mcnc.org
  'mcnc-mongo-test mcnc-shard-test':
    Hostname: snapp-shard-test-01.globalnoc.mcnc.org

  # nagios
  'mcnc-mon-test mcnc-nagios-test':
    Hostname: mon-test-01.globalnoc.mcnc.org
  'mcnc-mon-1 mcnc-nagios-1 mcnc-mon mcnc-nagios':
    Hostname: mon-01.globalnoc.mcnc.org
  'mcnc-mon-2 mcnc-nagios-2':
    Hostname: mon-02.globalnoc.mcnc.org

  # portal servers
  'mcnc-grafana-1 mcnc-grafana mcnc-portal-1 mcnc-portal':
    Hostname: snapp-portal-01.globalnoc.mcnc.org
  'mcnc-grafana-2 mcnc-portal-2':
    Hostname: snapp-portal-02.globalnoc.mcnc.org
  'mcnc-grafana-test mcnc-portal-test':
    Hostname: snapp-portal-test-01.globalnoc.mcnc.org

  # rabbit servers
  'mcnc-rabbit-1 mcnc-rabbit':
    Hostname: snapp-rabbit-01.globalnoc.mcnc.org
  mcnc-rabbit-2:
    Hostname: snapp-rabbit-02.globalnoc.mcnc.org
  mcnc-rabbit-test:
    Hostname: snapp-rabbit-test-01.globalnoc.mcnc.org

  # TSDS services servers
  'mcnc-services-1 mcnc-services':
    Hostname: snapp-services-01.globalnoc.mcnc.org
  mcnc-services-2:
    Hostname: snapp-services-02.globalnoc.mcnc.org
  mcnc-services-test:
    Hostname: snapp-services-test-01.globalnoc.mcnc.org

  # SNAPP/SIMP servers
  'mcnc-snapp-1 mcnc-simp-1 mcnc-snapp mcnc-simp':
    Hostname: snapp-collector-01.globalnoc.mcnc.org
  'mcnc-snapp-2 mcnc-simp-2':
    Hostname: snapp-collector-02.globalnoc.mcnc.org
  mcnc-snapp-ncren:
    Hostname: snapp.ncren.net
  'mcnc-snapp-test mcnc-simp-test':
    Hostname: snapp-collector-test-01.globalnoc.mcnc.org

  # OneNet hosts

  # carto hosts
  onenet-carto:
    Hostname: carto.noc.onenet.net

  # portal servers
  onenet-grafana:
    Hostname: grafana.noc.onenet.net

  # SNAPP servers
  onenet-snapp:
    Hostname: snapp.noc.onenet.net

  # OSHEAN hosts

  # SNAPP/SIMP servers
  'oshean-snapp oshean-simp':
    Hostname: snapp.oshean.org

use_tmux: true
