---
aliases:
  puppet: 'sudo /opt/puppetlabs/bin/puppet'
  socks5: 'ssh -D 17798 -S /tmp/.ssh-skip-socks5-jdratlif -M -fN skip.grnoc.iu.edu; export SOCKS5_PROXY="localhost:17798"'
  socks5_kill: 'ssh -S /tmp/.ssh-skip-socks5-jdratlif -O exit skip.grnoc.iu.edu'

functions:
  p:
    - >-
      if [[ -z "$1" ]]; then action="run"; else action=$1; shift; fi
    - >-
      cmd="sudo /opt/puppetlabs/bin/puppet"
    - >-
      test_mode="--noop"
    - >-
      ignore_lock="--agent_disabled_lockfile=/nonexisting"
    - >-
      agent="agent --test"
    - >-
      log="tee ~/puppet.log"
    - >-
      if [[ $action = "env" ]]; then grep environment /etc/puppetlabs/puppet/puppet.conf | awk "{print \$3}"
    - >-
      elif [[ $action = "enabled" ]]; then
    - >2-
        msg=$(sudo cat /opt/puppetlabs/puppet/cache/state/agent_disabled.lock 2>/dev/null)
    - >2-
        if [[ -z $msg ]]; then echo "puppet is enabled"
    - >2-
        else echo "puppet is disabled: $(echo $msg | jq .disabled_message)"
    - >2-
        fi
    - >-
      elif [[ $action = "run" ]]; then $cmd $agent "$@" | $log
    - >-
      elif [[ $action = "test" ]]; then $cmd $agent $noop $ignore_lock "$@" | $log
    - >-
      elif [[ $action = "force" ]]; then $cmd $agent $ignore_lock "$@" | $log
    - >-
      elif [[ $action = "lookup" ]]; then $cmd lookup --merge deep --node "$@"
    - >-
      elif [[ $action = "disable" ]]; then
    - >2-
        if [[ -z "$1" ]]; then msg="testing"; else msg=$1; fi
    - >2-
        $cmd agent --disable "$(date '+%Y-%m-%d') $(whoami) - $msg"
    - >-
      else echo "unrecognized action ${action}"
    - >-
      fi
  perl_libs:
    - >-
      MY_LIBS=$(grep '^use' $1 | tr -d '\n')
    - >-
      perl -M'Data::Dump qw(pp)' -e "${MY_LIBS} pp(\%INC);"

gitconfig:
  name: 'John Ratliff'
  email: 'jdratlif@globalnoc.iu.edu'
  credentials:
    - name: 'https://github.grnoc.iu.edu'
      username: jdratlif
      helper: 'cache --timeout 43200'
