---
aliases:
  p: 'sudo /opt/puppetlabs/puppet/bin/puppet agent --test'
  p_environment: >-
    grep environment /etc/puppetlabs/puppet/puppet.conf | awk "{print \$3}"
  p_enabled: >-
    sudo test -f /opt/puppetlabs/puppet/cache/state/agent_disabled.lock;
    if test $? -eq 0; then
    echo "puppet is disabled";
    sudo cat /opt/puppetlabs/puppet/cache/state/agent_disabled.lock
    | awk -F: "{print \$2}"
    | sed -e '\''s/["}]//g'\'';
    else
    echo "puppet is enabled";
    fi
  p_lookup: 'sudo /opt/puppetlabs/puppet/bin/puppet lookup --merge deep --node'
  p_force: 'sudo /opt/puppetlabs/puppet/bin/puppet agent -t --agent_disabled_lockfile=/nonexisting'
  p_test: 'sudo /opt/puppetlabs/puppet/bin/puppet agent -t --noop --agent_disabled_lockfile=/nonexisting'
  socks5: 'ssh -D 17798 -S /tmp/.ssh-skip-socks5-jdratlif -M -fN skip.grnoc.iu.edu; export SOCKS5_PROXY="localhost:17798"'
  socks5_kill: 'ssh -S /tmp/.ssh-skip-socks5-jdratlif -O exit skip.grnoc.iu.edu'

gitconfig:
  name: 'John Ratliff'
  email: 'jdratlif@globalnoc.iu.edu'
  credentials:
    - name: 'https://github.grnoc.iu.edu'
      username: jdratlif
      helper: 'cache --timeout 43200'

ssh_authorized_keys:
  - 'ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAgEAsJAZqYykuMPnE2yocIeXHxq9usy590RQZ1Ss/uQbsbnxtS9gvowitNc2lH2jwauB7SCP4VJAUHOwR5p5AbD3Vghy0n39d9+FWzDdgBTeFwDlxjSRu+f7ttdtzCHEPkqx9SOpdBwzV1OVAMYoJ04gon/n3nHAxjOeJpS2BSkPY4Yd7K065PkCLztGHkZbz7bTlUOUtaVbLRW2oHkhsrzQECNLsBO5XV/N49uvQSYoj3ivCpVtsSEO9BGEqOe24pFh7BWS23DSD3cdFn71bL/L+Tlv3Xv7QWSTcJRaSjbxn4TZCMyKEIpwt424LWzs0LnV5hjr37PpBR1jgoU33rOWXxOW2rmZTl+IQZozdoWTiIbUeDHMPRp88NJO5lb87vRReB0lEZaaeeuo4aomWDPDQCpUvgGMqTm1D1/LUckLUr7+DvDlyNOC6pBT0dw3Zp8OAdimfQ9CBEX7SjzmWeNSjkXGCoGg6I1+M2DZv9RJ/pvNZyLzrAdfTrZeqrW/A5cozidZIwNFDj6im8MOfzvZxED+JuoUkJEfbMEZvm07SqaWZQj/FhcRsPEURy69lzKFJvW1bzUI10DErIRU4FcIeN7F6PUWwoxNxV/CufSJpx0+4+vrLpgXQobJlhKxwgtObyGey4WkAo7ErwxaeJ4lI6e5NunoyTzyrmJicllXO4s= rsa-key-20160308'
  - 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDVyqUuMjemV/iDmvzoPVAhRnBPqgNhSXWs5HvzILj74 john@jdratlif-yoga2'
  - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDF3sAeL18haafdzan6fJFhj4sSJa9h9NuEvv+96ZhymYai2qkN1BlkpFZxwOBtKJdaPUwVrbduMBmvHcGYgvBJmdmHS2EupTWGqz9nmiklnP9r9gDS2mtU0QrkAGQqyC7zYLjXWaFR5tUiD19mNlrb2+tlPzy1DlwJQphZ33y4Qbm6KgzS41ufJQkpRpoM1wvEacSXrTvpx8hx9oFvFzvxxnPjkEH6g+birQa11vkD6C7I0YBDuJx4mzU+/1biKZLQTSOk+zfsfFWj5v4PKeS8aXcBebj/4MveVfidJ9wLejKzDQ5z+LqD/5pp8l9RpLyWwrEW0/Kb9/mTyzI7/O1ty8IjAzs9U5EfSuTuOJhFGQbvC0g6v6CAeZFtPOAHZEMmKwz+7RYHJfLVldenLz71pf5eeJ8Laja7e0Y3rmVL5vKNQ7KeuLQMjAA2WM5x0IJNcipr6WqAUnNcuDSvtUFuNdUvYZGUQUeWbr5FvuY/P7SXD1cKN/ZCirfFK3JEZl0mzwKOdGOS43zIm5U9eKa4U085BPcCRTej6UjrNmQ0XvIZLzYvFJrA3izJGlQzKkIfUXYZIewdQinFqkM1AYY6ZJsGukPqJbtv0oihsVcTqUWZxG0Z4U3H8e4+AnifjC0EjxTz47maVyLvE1nJTMnbxYJKAuxWuZMju2qATxQA5Q== /home/jdratlif/.ssh/id_rsa'
