---
aliases:
  puppet: 'sudo /opt/puppetlabs/bin/puppet'
  socks5: 'ssh -D 17798 -S /tmp/.ssh-skip-socks5-jdratlif -M -fN skip.grnoc.iu.edu; export SOCKS5_PROXY="localhost:17798"'
  socks5_kill: 'ssh -S /tmp/.ssh-skip-socks5-jdratlif -O exit skip.grnoc.iu.edu'

functions:
  p:
    - >-
      if [[ -z "$1" ]]; then action="run"; else action=$1; shift; fi
    - >-
      puppet="sudo /opt/puppetlabs/bin/puppet"
    - >-
      ignore_lock="--agent_disabled_lockfile=/nonexisting"
    - >-
      log="tee $HOME/puppet.log"
    - >-
      if [[ $action = "env" ]]; then grep environment /etc/puppetlabs/puppet/puppet.conf | awk "{print \$3}"
    - >-
      elif [[ $action = "enabled" ]]; then
    - >2-
        msg=$(sudo cat /opt/puppetlabs/puppet/cache/state/agent_disabled.lock 2>/dev/null)
    - >2-
        if [[ -z $msg ]]; then echo "puppet is enabled"
    - >2-
        else echo "puppet is disabled: $(echo $msg | jq .disabled_message)"
    - >2-
        fi
    - >-
      elif [[ $action = "run" ]]; then my_cmd="$puppet agent --test \"$@\" 2>&1 | $log"; echo "running [$my_cmd]..."; eval $my_cmd
    - >-
      elif [[ $action = "test" ]]; then my_cmd="$puppet agent --test $ignore_lock --noop \"$@\" 2>&1 | $log"; echo "running [$my_cmd]..."; eval $my_cmd
    - >-
      elif [[ $action = "force" ]]; then my_cmd="$puppet agent --test $ignore_lock \"$@\" 2>&1 | $log" ; echo "running [$my_cmd]..."; eval $my_cmd
    - >-
      elif [[ $action = "lookup" ]]; then my_cmd="$puppet lookup --merge deep --node \"$@\""; echo "running [$my_cmd]..."; eval $my_cmd
    - >-
      elif [[ $action = "disable" ]]; then
    - >2-
        if [[ -z "$1" ]]; then msg="testing"; else msg=$1; fi
    - >2-
        my_cmd="$puppet agent --disable \"$(date '+%Y-%m-%d') $(whoami) - $msg\""; echo "running [$my_cmd]..."; eval $my_cmd
    - >-
      elif [[ $action = "enable" ]]; then my_cmd="$puppet agent --enable"; echo "running [$my_cmd]..."; eval $my_cmd
    - >-
      else echo "unrecognized action ${action}"
    - >-
      fi
  perl_libs:
    - >-
      MY_LIBS=$(grep '^use' $1 | tr -d '\n')
    - >-
      perl -M'Data::Dump qw(pp)' -e "${MY_LIBS} pp(\%INC);"

gitconfig:
  name: 'John Ratliff'
  email: 'jdratlif@globalnoc.iu.edu'
  credentials:
    - name: 'https://github.grnoc.iu.edu'
      username: jdratlif
      helper: 'cache --timeout 43200'
