---
aliases:
  p: 'sudo /opt/puppetlabs/puppet/bin/puppet agent --test'
  p_environment: >-
    grep environment /etc/puppetlabs/puppet/puppet.conf | awk "{print \$3}"
  p_enabled: >-
    sudo test -f /opt/puppetlabs/puppet/cache/state/agent_disabled.lock;
    if test $? -eq 0; then
    echo "puppet is disabled";
    sudo cat /opt/puppetlabs/puppet/cache/state/agent_disabled.lock
    | awk -F: "{print \$2}"
    | sed -e '\''s/["}]//g'\'';
    else
    echo "puppet is enabled";
    fi
  p_lookup: 'sudo /opt/puppetlabs/puppet/bin/puppet lookup --merge deep --node'
  p_force: 'sudo /opt/puppetlabs/puppet/bin/puppet agent -t --agent_disabled_lockfile=/nonexisting'
  p_test: 'sudo /opt/puppetlabs/puppet/bin/puppet agent -t --noop --agent_disabled_lockfile=/nonexisting'
  socks5: 'ssh -D 17798 -S /tmp/.ssh-skip-socks5-jdratlif -M -fN skip.grnoc.iu.edu; export SOCKS5_PROXY="localhost:17798"'
  socks5_kill: 'ssh -S /tmp/.ssh-skip-socks5-jdratlif -O exit skip.grnoc.iu.edu'
  svim: 'sudo env HOME=~ vim'

gitconfig:
  name: 'John Ratliff'
  email: 'jdratlif@globalnoc.iu.edu'
  credentials:
    - name: 'https://github.grnoc.iu.edu'
      username: jdratlif
      helper: 'cache --timeout 43200'

ssh_authorized_keys:
  - 'ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAgEAsJAZqYykuMPnE2yocIeXHxq9usy590RQZ1Ss/uQbsbnxtS9gvowitNc2lH2jwauB7SCP4VJAUHOwR5p5AbD3Vghy0n39d9+FWzDdgBTeFwDlxjSRu+f7ttdtzCHEPkqx9SOpdBwzV1OVAMYoJ04gon/n3nHAxjOeJpS2BSkPY4Yd7K065PkCLztGHkZbz7bTlUOUtaVbLRW2oHkhsrzQECNLsBO5XV/N49uvQSYoj3ivCpVtsSEO9BGEqOe24pFh7BWS23DSD3cdFn71bL/L+Tlv3Xv7QWSTcJRaSjbxn4TZCMyKEIpwt424LWzs0LnV5hjr37PpBR1jgoU33rOWXxOW2rmZTl+IQZozdoWTiIbUeDHMPRp88NJO5lb87vRReB0lEZaaeeuo4aomWDPDQCpUvgGMqTm1D1/LUckLUr7+DvDlyNOC6pBT0dw3Zp8OAdimfQ9CBEX7SjzmWeNSjkXGCoGg6I1+M2DZv9RJ/pvNZyLzrAdfTrZeqrW/A5cozidZIwNFDj6im8MOfzvZxED+JuoUkJEfbMEZvm07SqaWZQj/FhcRsPEURy69lzKFJvW1bzUI10DErIRU4FcIeN7F6PUWwoxNxV/CufSJpx0+4+vrLpgXQobJlhKxwgtObyGey4WkAo7ErwxaeJ4lI6e5NunoyTzyrmJicllXO4s= rsa-key-20160308'
  - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC/mA8Y0PLP4xGX3kqO2LYbvVoPApV/fzikVgHDsPFAFwBQpgx54bnqu+vHbHp81z8DhRBde9EvtAmsmGMxzsNPYVbcoVRPTymwH5QMA/aXPUCvHgUsPysNaZhC/KlG8vYI7wTmfAbomXjLMKH3VHTwr/UBwFGfgWhOF93llYoJUflaElGDHqAs30/xB90gY2Q11tYNw66nTleuZLRrtvxHiEg4TP/MmpwrmtqSEOAr1gySgACXqHN+fPxG1CWffQm36yqJw9vCKFkaFL4HAwHBL6Hf4UWEXHC140K5SA8KudvwwcIgVZphuV8XYl+jXH4uuruNlfvzPR8uevytxdMXvqcyDjmmw63x+TJaqtuyjyRBf5WK6VbXAZXHGWk5/C7mAB0POsQdivU/oyhX5s15aJVheHNSNQD5++WfkRbe98nN7BGTr2wsMhAxhMNWXb9lHcD2g+QxN2zAo9ym5Ty0QehhosV742WVtTwEISwy7c8MVAHLp5N8HuIJBsfJKZfwG087VH+8KffqwUU3ZRnyE7yEH3kSZ9Wl0vj54dkDeYPJZICJWo4kztCe+vgXg7J9MjIdhygJFXBcw4+hsjCAd9BHLLhGiYIiwc9BnjZzzVNvnXz+MaDFqxY3+knKbiV9Q2h80RpzIJopYhh3BYMuLbys4rzUGX5ShXSlU0K5nQ== /home/jdratlif/.ssh/id_rsa'
  - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDGVuAwXXNQ0ml1Sn/hwSvliT/4qF5wrn2yuZEzteJnmlsSAJe3JUkADZ2Vsy266paJRxeorcIOV9jUoz7dfNvvK4719NWQ5zhKxULLtcnLAKl5/OgdTTGk3QpKusbnKNLOzZDOaElSseruBo4bx680nPuBQbaAt7Mpga1YtWoMcYm/HSP8xu1ZekpCAe+2vM/du4buO3xQSSULtd+hIVRBH1iw/IR1O8o5jF4dozgAisBk0mFJEGen0JH0f+QnSVDFostM42tqd8oXyCIack2Kn1vMc7M1OR/Wo5LP2QI0bfDKkGGRZjLV1Bd+Pa4hAYRX9kFezacCsBsZWxxdOgDIpflfpWitras6GuIUgTs375gnwW97ABK32YIg9t384NKsqnVCGiVMWxF5YobiJDft2sUyKysvwxNIgbb9/XqbLe6L5AnpLrpgXLesTLDAPG0r/V4cS3eNZgJEMKgBcPXkS8yQMfvs/PX+A4XVVanv5wOSJs7gnfXmKb4c4pQuDgPsgCyOpK2344jztfWKk2lTVq3I2z0MZdMjiJLeaGz6/HzvdjtGCbNMxD63b+JkmxR3Py49TM6LxJgH7cvQYwtDUxbcDnpP17kXnFyftqQBof2PRzedKqbKlRxarF/tj8/oy0+i00b75rFqUToaUcNcG2Lrk5HIzIMSaGiFdGJ3iw== john@LAPTOP-5CKKNFH6'
