---
aliases:
  myansible: 'eval $(ssh-agent) ; sudo -E ssh-add /home/syscnf/.ssh/id_rsa'

ansible_connection: local

functions:
  config_host:
    - name=$1
    - shift
    - ansible-playbook main.yaml -e "host_override=$name" "$@"

ssh_host_common_configs:
  ControlMaster: 'auto'
  ControlPath: '~/.ssh/%r@%h:%p'

ssh_host_configs:
  dns:
    Hostname: 'mysql.bldc.nwave.noaa.gov'
  puppet:
    Hostname: 'dist.bldc.nwave.noaa.gov'

use_tmux: true
