---
- name: Copy vimrc
  ansible.builtin.copy:
    src: main.vim
    dest: "{{ home_dir }}/.vimrc"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: "0644"

- name: Ensure ownership of viminfo
  ansible.builtin.file:
    path: "{{ home_dir }}/.viminfo"
    state: file
    owner: "{{ user }}"
    group: "{{ group }}"
  failed_when: false

- name: Create vim directory
  ansible.builtin.file:
    path: "{{ home_dir }}/.vim"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: "0755"

- name: Copy yaml plugin
  ansible.builtin.copy:
    src: plugins/yaml.vim
    dest: "{{ home_dir }}/.vim"
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: "0644"
