---
- name: copy vimrc
  copy:
    src: main.vim
    dest: '{{ home_dir }}/.vimrc'
    owner: '{{ user }}'
    group: '{{ group }}'
- name: ensure ownership of viminfo
  file:
    path: '{{ home_dir }}/.viminfo'
    state: file
    owner: '{{ user }}'
    group: '{{ group }}'
  failed_when: false
- name: create vim directory
  file:
    path: '{{ home_dir }}/.vim'
    state: directory
    owner: '{{ user }}'
    group: '{{ group }}'
- name: copy yaml plugin
  copy:
    src: plugins/yaml.vim
    dest: '{{ home_dir }}/.vim'
    owner: '{{ user }}'
    group: '{{ group }}'
